### ISSUE TITLE
unicode_alternates and unicode in file names

### ISSUE THREAD

**Issue by otopba** [UltimateZero/EmojiOneJava#1]
Hi! You don't take into account when you display that image stored in unicode and not unicode_alternates. For example, you cannot open emoji has unicode_alternates = "0035-fe0f-20e3", unicode="0035-20e3". Because you EmojiEntry always return only the last enicode getLastUnicode()

**Comment by UltimateZero** [comment]
Hi!
Sorry for the late response.
It should be working correctly now. the reason I use getLastUnicode() is because the image filename is using it.
